### PR TITLE
Add basic gen

### PR DESCRIPTION
**Pull request by mehdi-parvizi**

### CODE REVIEW

**Comment by abolfazl8131** [comment]
Thanks for your contribution. We don't need any caching in the project, it can cause a bad response. please remove it

**Comment by mehdi-parvizi** [comment]
> Thanks for your contribution. We don't need any caching in the project, it can cause a bad response. please remove it

which caching are you referring to?

**Comment by abolfazl8131** [comment]
when I hit the api, i give a similar outputs with several different inputs, and it behaves something like caching

**Comment by abolfazl8131** [comment]
Thank you. it works fine

**Pull request merged**
