### PR TITLE
Redesign ui

### PR DESCRIPTION
**Pull request by MiladSadeghi**
<details>
  <summary>Basic Page</summary>
  
Screenshot 2024-11-29 195603
</details>

<details>
 <summary>Bug Fix Page</summary>

Screenshot 2024-11-29 195930
</details>

<details>
 <summary>Terraform Template Page</summary>

Screenshot 2024-11-29 200023
</details>

<details>
 <summary>Installation Page</summary>

Screenshot 2024-11-29 200059
</details>

<details>
 <summary>Helm Template Page</summary>

Screenshot 2024-11-29 200135
</details>

### CODE REVIEW

**Comment by abolfazl8131** [comment]
it seems nice, Thank you

**Comment by mohammadll** [comment]
@MiladSadeghi You did a great job! I really like what you’ve done. I just have two suggestions to add:

1. When I click the "Generate Terraform" button, it would be better to change its label to something like "Wait..." during the process.
2. Would it be possible for you to add a light/dark theme toggle option to the UI?

**Comment by MiladSadeghi** [comment]
I’ve implemented the suggested changes:

1. The "Generate Terraform" button now updates its label to "Wait..." during the process.
2. Added a light/dark theme toggle option to the UI.

**Comment by mohammadll** [comment]
@MiladSadeghi Wow, I appreciate what you did!

**Pull request merged**
